### ISSUE TITLE
未提出・未修整部分提出依頼

### ISSUE THREAD

**Issue by seiga** [Yoichiro-Shimizu/Challenge#1]
- challenge0のアルゴリズムの課題を提出してください
- challenge1_7.phpの修正を行ってください
- challenge2_7_8.phpの修正を行ってください
- challenge2_9.phpの修正を行ってください
- challenge2_10.phpを提出してください
- challenge3を提出してください
- challenge4_5.phpを提出してください
- challenge4_10.phpを提出してください
- challenge5_3.phpの修正を行ってください
- challenge5_4.phpの修正を行ってください
- challenge5_6.phpを提出してください
- challenge5_7.phpの修正を行ってください
- challenge7_1.phpの修正を行ってください
- challenge7_2.phpの修正を行ってください
- challenge7_5.phpの修正を行ってください
- challenge7の課題8,9,10,11,12,13を提出してください
- challenge8を提出してください

**Comment by Yoichiro-Shimizu** [comment]
メッセージ拝見しました。
ご指摘参考にさせて頂き、進めさせて頂きたいと思います。
